---
- hosts: Debian
  become: yes
  tasks:
    - name: Install sudo, Midnight Commander, htop, Openjdk-11-jdk, fail2ban, git
      ansible.builtin.apt:
        update_cache: yes
        pkg:
          - sudo
          - mc
          - htop
          - openjdk-11-jdk
          - fail2ban
          - git

    - name: Add fgery to sudo
      ansible.builtin.user:
        name: fgery
        groups: sudo
        append: yes

    - name: Create udemx user with /opt/udemx home folder
      ansible.builtin.user:
        name: udemx
        home: /opt/udemx

    - name: Install Openjdk-8-jre-headless
      ansible.builtin.apt:
        deb: http://security.debian.org/debian-security/pool/updates/main/o/openjdk-8/openjdk-8-jre-headless_8u332-ga-1~deb9u1_amd64.deb
    
    - name: Install Openjdk-8-jre
      ansible.builtin.apt:
        deb: http://security.debian.org/debian-security/pool/updates/main/o/openjdk-8/openjdk-8-jre_8u332-ga-1~deb9u1_amd64.deb
    
    - name: Install Openjdk-8-jdk-headless
      ansible.builtin.apt:
        deb: http://security.debian.org/debian-security/pool/updates/main/o/openjdk-8/openjdk-8-jdk-headless_8u332-ga-1~deb9u1_amd64.deb

    - name: Install Openjdk-8-jdk
      ansible.builtin.apt:
        deb: http://security.debian.org/debian-security/pool/updates/main/o/openjdk-8/openjdk-8-jdk_8u332-ga-1~deb9u1_amd64.deb

    - name: Change Javac version from 11 to 8
      ansible.builtin.shell: update-alternatives --set javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac

    - name: Download Docker
      ansible.builtin.get_url:
        url: https://get.docker.com
        dest: /tmp/get-docker.sh
        mode: '0770'

    - name: Docker install
      ansible.builtin.shell: sh /tmp/get-docker.sh
    
    - name: Start and enable docker
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true
    
    - name: Start Hello World container
      ansible.builtin.shell: docker run hello-world
    
    - name: Config Git user
      ansible.builtin.shell: git config --global user.name udemx@udemx.eu

    - name: Copy Git credentials
      ansible.builtin.copy:
        src: /home/fgery/.ssh/id_rsa
        dest: /home/fgery/.ssh/id_rsa
        owner: fgery
        mode: '0700'
    
    - name: Git checkout
      ansible.builtin.git:
        repo: 'git@github.com:faragogergely/udemx.git'
        dest: /tmp/udemx

    - name: Start Docker Registry
      ansible.builtin.shell: docker compose -f /tmp/udemx/Registry/docker-compose.yml up -d

    - name: Start Jenkins
      ansible.builtin.shell: docker compose -f /tmp/udemx/Jenkins/docker-compose.yml up -d

 



  
