FROM mariadb:latest
ENV MARIADB_USER=udemx
ENV MARIADB_PASSWORD=udemxpw 
ENV MARIADB_ROOT_PASSWORD=rootpw
ENV MARIADB_DATABASE=udemx-db
RUN echo '[client]' >> /etc/mysql/my.cnf
RUN echo 'user = root' >> /etc/mysql/my.cnf
RUN echo 'password = "rootpw"' >> /etc/mysql/my.cnf
